# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PipeLine to develop

on:
  push:
    branches: [ 'feature/*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --max-line-length=120 --ignore=E402,W503,E722 .

    # - name: Publish to Registry
    #   uses: HurricanKai/Publish-Docker-Github-Action@v2
    #   with:
    #     name: jichu20/rotate-image:latest
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     dockerfile: dockerfile
    # - name: build docker image
    #   id: build
    #   uses: docker/build-action@v1
    #   with:
    #     repository: jichu20/rotate-image
    #     tags: latest



    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build . --file dockerfile --tag jichu20/rotate-image:latest
    - name: Push the tagged Docker image
      run: docker pushjichu20/rotate-image:latest

